version: "3.8"
services:
  gachana_db:
    image: mysql:latest
    container_name: gachana_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Gachana_DB
      MYSQL_USER: gachana
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./config_files/gachana_initDB.sql:/docker-entrypoint-initdb.d/gachana_initDB.sql

volumes:
  db_data:
    name: gachana_db_volume
