openapi: 3.0.0
info:
  title: MarketService API
  description: API for managing market auctions in the Gacha Online application.
  version: "1.0.0"
servers:
  - url: http://localhost/market
    description: Localhost server
paths:
  /list:
    get:
      summary: Get all market items
      description: Retrieve a list of all items currently listed in the market.
      responses:
        "200":
          description: List of market items
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      description: Unique identifier for the market item.
                    gacha_id:
                      type: integer
                      description: ID of the Gacha item.
                    user_id:
                      type: integer
                      description: ID of the user who listed the item.
                    init_value:
                      type: number
                      format: float
                      description: Initial auction value.
                    value_last_offer:
                      type: number
                      format: float
                      description: Value of the last offer.
                    start_date:
                      type: string
                      format: date
                      description: Start date of the auction.
                    end_date:
                      type: string
                      format: date
                      description: End date of the auction (if applicable).
  /new-auction:
    post:
      summary: Create a new auction
      description: Publish a Gacha item for sale on the market.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                gacha_id:
                  type: integer
                  description: ID of the Gacha item.
                end_date:
                  type: string
                  format: date
                  description: Auction end date.
                init_value:
                  type: number
                  format: float
                  description: Initial value of the auction.
      responses:
        "201":
          description: Auction successfully created.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Item listed for sale."
  /new-bid:
    post:
      summary: Place a bid on an auction
      description: Submit or update a bid on an auction.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                market_id:
                  type: integer
                  description: ID of the market auction.
                offer_value:
                  type: number
                  format: float
                  description: Value of the bid.
      responses:
        "200":
          description: Bid placed or updated successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Offer placed successfully."
  /{market_id}/offers:
    get:
      summary: Get offers for a market
      description: Retrieve all offers for a specific market auction.
      parameters:
        - name: market_id
          in: path
          required: true
          schema:
            type: integer
          description: ID of the market auction.
      security:
        - bearerAuth: []
      responses:
        "200":
          description: List of offers
          content:
            application/json:
              schema:
                type: object
                properties:
                  market_id:
                    type: integer
                  offers:
                    type: array
                    items:
                      type: object
                      properties:
                        offer_id:
                          type: integer
                        user_id:
                          type: integer
                        offer_value:
                          type: number
                          format: float
  /accept:
    post:
      summary: Accept an offer
      description: Accept a bid and finalize the auction.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                market_id:
                  type: integer
                buyer_id:
                  type: integer
      responses:
        "200":
          description: Offer accepted successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Offer accepted successfully."
  /history:
    get:
      summary: Get transaction history
      description: Retrieve the market transaction history for the authenticated user.
      security:
        - bearerAuth: []
      responses:
        "200":
          description: User transaction history
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    transaction_id:
                      type: integer
                    user_seller_id:
                      type: integer
                    user_buyer_id:
                      type: integer
                    gacha_value:
                      type: number
                      format: float
                    date:
                      type: string
                      format: date
  /history/all:
    get:
      summary: Get all transaction history (Admin)
      description: Retrieve the full market transaction history.
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Complete transaction history
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    transaction_id:
                      type: integer
                    user_seller_id:
                      type: integer
                    user_buyer_id:
                      type: integer
                    gacha_value:
                      type: number
                      format: float
                    date:
                      type: string
                      format: date
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
