name: Test API Gachana

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Start application with Docker Compose
      run: |
        docker compose up -d --build

    - name: Wait for services
      run: |
        echo "Waiting for services to be ready..."
        sleep 15

    - name: Install Newman
      run: |
        npm install -g newman

    - name: Run Postman tests
      env:
        BASE_URL: "http://localhost"
      run: |
        newman run docs/integrationTests/GachanaIntegrationTests.postman_collection.json \
          --environment docs/integrationTests/env.postman_environment.json \
          --delay-request 1000 \
          --timeout 60000 \
          --reporters cli

    - name: Stop application
      if: always()
      run: |
        docker compose down

